apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: flask-app-svcmonitor
    namespace: monitoring
    labels:
        release: prometheus
spec:
    selector:
        matchLabels:
            app: flask-app
    namespaceSelector:
        matchNames:
            - default
    endpoints:
        - port: http
          interval: 15s
          path: /metrics
