apiVersion: v1
kind: Service
metadata:
    name: flask-app-service
    namespace: default
    labels:
        app: flask-app
spec:
    selector:
        app: flask-app
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 80
    type: NodePort
